<template>
  <div>
    <v-dialog v-model="dialog" fullscreen hide-overlay persistent>
      <v-card
          style="
        border: none !important;
        box-shadow: none !important;
        background-color: var(--primary-background);
      "
      >
        <v-content>
          <v-container fluid>
            <v-layout
                align-center
                justify-center
                style="background-color: var(--primary-background) !important"
            >
              <v-flex class="elevation-0" lg3 md4 sm8 xs12>
                <v-layout style="min-height: 150px; padding-top: 3%">
                  <v-flex class="text-center" xs12>
                    <img
                        :src="require('@/assets/logo.png')"
                        class="mb-5 cursor-pointer"
                        width="125px"
                    />
                  </v-flex>
                </v-layout>
                <v-spacer></v-spacer>
                <v-card-text class="mt-10">
<!--                  <template v-if="type === 'twoFactorAuth'">-->
                  <template>
                    <v-row justify="center">
                      <v-col cols="1">
                        <v-icon>stay_current_portrait</v-icon>
                      </v-col>
                      <v-col cols="11">
                        <h2>
                          Enter the 6-digit code generated by your
                          authentication
                        </h2>
                      </v-col>
                    </v-row>
                    <v-row justify="center">
                      <TFACode :callback="tfaCodeCallback"></TFACode>
                    </v-row>
                  </template>

<!--                  <template v-if="type === 'recover'">-->
<!--                    <v-row justify="center">-->
<!--                      <v-col cols="12">-->
<!--                        <h2>-->
<!--                          Lost access to your phone? We've got cou covered 💪-->
<!--                        </h2>-->
<!--                        <p class="mt-2">-->
<!--                          Type your recovery code bellow and we’ll get you back-->
<!--                          on track in no time-->
<!--                        </p>-->
<!--                      </v-col>-->
<!--                    </v-row>-->
<!--                    <v-row justify="center">-->
<!--                      <v-col cols="12">-->
<!--                        <v-form-->
<!--                            ref="validationRecover"-->
<!--                            v-model="valid"-->
<!--                            lazy-validation-->
<!--                        >-->
<!--                          <v-text-field-->
<!--                              ref="initFocus"-->
<!--                              v-model="recover"-->
<!--                              :rules="[v => !!v || 'This field is required']"-->
<!--                              :validate-on-blur="true"-->
<!--                              color="revapp"-->
<!--                              label="Recovery Code"-->
<!--                          ></v-text-field>-->
<!--                        </v-form>-->
<!--                      </v-col>-->
<!--                    </v-row>-->
<!--                  </template>-->
                </v-card-text>

                <v-card-actions
                    style="border-top: 0px solid var(--primary-background)"
                >
                  <v-row dense>
                    <v-col cols="12">
                      <v-btn
                          block
                          color="authButtonConfirm"
                          name="actionButton"
                          @click="performAction"
                      >Verify
                      </v-btn
                      >
                    </v-col>
                    <v-col cols="7">
                      <v-btn
                          color="authButtonSecond"
                          elevation="0"
                          name="cancelButton"
                          small
                          style="float: left"
                          @click="close"
                      >Cancel
                      </v-btn
                      >
                    </v-col>
<!--                    <v-col-->
<!--                        v-if="type === 'twoFactorAuth'"-->
<!--                        class="text-right"-->
<!--                        cols="5"-->
<!--                    >-->
<!--                      <v-btn-->
<!--                          color="authButtonSecond"-->
<!--                          elevation="0"-->
<!--                          name="cancelButton"-->
<!--                          small-->
<!--                          style="border-bottom: 1px solid white"-->
<!--                          @click="type = 'recover'"-->
<!--                      >Use my recovery code-->
<!--                      </v-btn-->
<!--                      >-->
<!--                    </v-col>-->
                  </v-row>
                </v-card-actions>
              </v-flex>
            </v-layout>
          </v-container>
        </v-content>
      </v-card>
    </v-dialog>
  </div>
</template>

<script lang="ts">
import Component from "vue-class-component";
import { MyVue } from "@/MyVue";
import { Emit, Prop } from "vue-property-decorator";
import TFACode from "@/presentation/view/Login/component/TFACode.vue";

@Component({
  components: {
    TFACode
  }
})
export default class TwoFactorAuthFormComponent extends MyVue {
  @Prop() private dialog!: boolean;
  @Prop() private email!: string;
  @Prop() private password!: string;

  name = "TwoFactorAuthDialogComponent.vue";
  sixDigitCode = "";
  valid = true;

  created() {
  }

  tfaCodeCallback(code: string) {
    this.sixDigitCode = code;
  }

  performAction() {
    console.log(this.email);
    console.log(this.password);

    if (this.sixDigitCode.length) {
      this.verify(this.sixDigitCode);
      console.log(this.email);
      console.log(this.password);
    }
  }

  @Emit("close-dialog")
  close() {
    this.clean();
    return false;
  }

  @Emit("loginWithTotp")
  verify(sixDigitCode: string) {
    this.clean();
    return sixDigitCode;
  }

  clean() {
    // this.type = "twoFactorAuth";
    this.sixDigitCode = "";
    this.valid = true;
  }
}
</script>

<style lang="scss" scoped></style>
